#!/bin/env node

const TypeDoc = require("typedoc");

async function main() {
    const app = new TypeDoc.Application();

    // If you want TypeDoc to load tsconfig.json / typedoc.json files
    app.options.addReader(new TypeDoc.TSConfigReader());
    app.options.addReader(new TypeDoc.TypeDocReader());

    app.bootstrap({
        // typedoc options here
        entryPoints: ["src/index.ts"],
        tsconfig: "tsconfig.json",
        exclude: "**/node_modules/**/*.*",
        excludeExternals: true,
        excludeInternal: true,
        readme: "README.md",
        name: "NestJS Aggregate Docs",
        theme: "default",
        emit: "both",
        githubPages: true,
    });

    const project = app.convert();

    if (project) {
        // Project may not have converted correctly
        const outputDir = "docs";

        // Rendered docs
        await app.generateDocs(project, outputDir);
        // Alternatively generate JSON output
        await app.generateJson(project, outputDir + "/documentation.json");
    }
}

main().catch(console.error);